In [2]:
from sklearn import preprocessing
import numpy as np 

X = np.array([[1, -1, 2],
              [2, 0, 0],
              [0, 1, 1]], dtype= float)
X

array([[ 1., -1.,  2.],
       [ 2.,  0.,  0.],
       [ 0.,  1.,  1.]])

In [3]:
X_scaled = preprocessing.scale(X)
X_scaled

array([[ 0.        , -1.22474487,  1.22474487],
       [ 1.22474487,  0.        , -1.22474487],
       [-1.22474487,  1.22474487,  0.        ]])

In [7]:
X_scaled.mean(axis=1)

array([0., 0., 0.])

In [6]:
X_scaled.mean(axis=1)

array([0., 0., 0.])

In [12]:
X.mean(axis=1)

array([0.66666667, 0.66666667, 0.66666667])

In [13]:
X.shape

(3, 3)