In [142]:
import numpy as np
import pandas as pd

In [143]:
# NumPy' main datatype is ndarray
array1 = np.array([1,2,3])
array1

array([1, 2, 3])

In [144]:
type(array1)

numpy.ndarray

In [145]:
array2 = np.array([[1, 2, 3],
                   [4, 5, 6]], dtype=float)

array3 = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],
                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]]])


In [146]:
array1.shape,array1

((3,), array([1, 2, 3]))

In [147]:
array2.shape, array2

((2, 3),
 array([[1., 2., 3.],
        [4., 5., 6.]]))

In [148]:
array3.shape, array3

((2, 3, 3),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [149]:
array1.ndim, array2.ndim, array3.ndim

(1, 2, 3)

In [150]:
array1.dtype, array2.dtype, array3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [151]:
array1.size, array2.size, array3.size

(3, 6, 18)

In [152]:
type(array1), type(array2), type(array3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [153]:
# Create a Dataframe from NumPy array
df = pd.DataFrame(array2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.0

In [154]:
ones = np.ones((2,3,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [155]:
ones.dtype

dtype('float64')

In [156]:
type(ones)

numpy.ndarray

In [157]:
zeros = np.zeros((3,1,3))
zeros

array([[[0., 0., 0.]],

       [[0., 0., 0.]],

       [[0., 0., 0.]]])

In [158]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [159]:
range_array =  np.random.randint(5, 10 , size=(2,3,3))
range_array

array([[[5, 8, 5],
        [8, 6, 8],
        [8, 5, 6]],

       [[9, 7, 6],
        [6, 7, 5],
        [7, 5, 9]]])

In [160]:
range_array.size

18

In [161]:
range_array.shape

(2, 3, 3)

In [162]:
random_array_2 = np.random.random((5, 3))

In [163]:
random_array_2.shape, random_array_2.size,random_array_2

((5, 3),
 15,
 array([[0.17671216, 0.59125735, 0.48926617],
        [0.54790778, 0.69952062, 0.24581116],
        [0.18662715, 0.11058315, 0.27405925],
        [0.01025004, 0.62935972, 0.29517231],
        [0.18728654, 0.09528805, 0.28375581]]))

In [164]:
# Presudo-random numbers
np.random.seed(2)

# 3. Viewing arrays and matrices 

In [165]:
np.unique(range_array)

array([5, 6, 7, 8, 9])

In [166]:
array1[0]

1

In [167]:
array2[0]

array([1., 2., 3.])

In [168]:
array3[0][0][1]

2

In [169]:
array3[:2, 0:2, 0:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [170]:
array4 = np.random.randint(10, size=(2,3,4,5))

In [171]:
array4

array([[[[8, 8, 6, 2, 8],
         [7, 2, 1, 5, 4],
         [4, 5, 7, 3, 6],
         [4, 3, 7, 6, 1]],

        [[3, 5, 8, 4, 6],
         [3, 9, 2, 0, 4],
         [2, 4, 1, 7, 8],
         [2, 9, 8, 7, 1]],

        [[6, 8, 5, 9, 9],
         [9, 3, 0, 0, 2],
         [8, 8, 2, 9, 6],
         [5, 6, 6, 6, 3]]],


       [[[8, 2, 1, 4, 8],
         [1, 6, 9, 5, 1],
         [2, 4, 7, 6, 4],
         [5, 8, 3, 0, 0]],

        [[5, 7, 5, 0, 8],
         [6, 5, 1, 7, 4],
         [3, 6, 1, 4, 0],
         [8, 5, 4, 2, 9]],

        [[7, 1, 9, 2, 1],
         [0, 7, 1, 8, 9],
         [0, 7, 0, 5, 2],
         [5, 1, 3, 3, 1]]]])

In [172]:
array4.shape, array4.ndim

((2, 3, 4, 5), 4)

In [173]:
# Get the first 4 numbers of the inner most arrays
array4[:,:3,:,:1]

array([[[[8],
         [7],
         [4],
         [4]],

        [[3],
         [3],
         [2],
         [2]],

        [[6],
         [9],
         [8],
         [5]]],


       [[[8],
         [1],
         [2],
         [5]],

        [[5],
         [6],
         [3],
         [8]],

        [[7],
         [0],
         [0],
         [5]]]])

## 4. Manipulating & Comparison arrays
### Arithmetic

In [174]:
array1

array([1, 2, 3])

In [175]:
ones_1=np.ones(3)
ones_1

array([1., 1., 1.])

In [176]:
# You can use (-)
array1 + ones_1

array([2., 3., 4.])

In [177]:
array1 * ones_1

array([1., 2., 3.])

In [178]:
array1

array([1, 2, 3])

In [179]:
array2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [180]:
array1 * array2

array([[ 1.,  4.,  9.],
       [ 4., 10., 18.]])

In [181]:
# How can you reshape array2 to be compatible with array3?
# Search: "How to reshape numpy array"
array2 * array3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
array1 / ones_1

array([1., 2., 3.])

In [ ]:
array2 / array1 

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [ ]:
# Floor division removes the decimals(rounds down)
array2 // array1

array([[1, 1, 1],
       [4, 2, 2]])

In [ ]:
array2 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [182]:
np.exp(array1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [183]:
np.log(array1)

array([0.        , 0.69314718, 1.09861229])