In [2]:
import numpy as np
import pandas as pd

In [3]:
# NumPy' main datatype is ndarray
array1 = np.array([1,2,3])
array1

array([1, 2, 3])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array2 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array3 = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],
                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]]])


In [6]:
array1.shape,array1

((3,), array([1, 2, 3]))

In [7]:
array2.shape, array2

((2, 3),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [8]:
array3.shape, array3

((2, 3, 3),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [9]:
array1.ndim, array2.ndim, array3.ndim

(1, 2, 3)

In [10]:
array1.dtype, array2.dtype, array3.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [11]:
array1.size, array2.size, array3.size

(3, 6, 18)

In [12]:
type(array1), type(array2), type(array3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [13]:
# Create a Dataframe from NumPy array
df = pd.DataFrame(array2)
df

0  1  2
0  1  2  3
1  4  5  6

In [14]:
ones = np.ones((2,3,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [15]:
ones.dtype

dtype('float64')

In [16]:
type(ones)

numpy.ndarray

In [17]:
zeros = np.zeros((3,1,3))
zeros

array([[[0., 0., 0.]],

       [[0., 0., 0.]],

       [[0., 0., 0.]]])

In [18]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [19]:
range_array =  np.random.randint(5, 10 , size=(2,3,3))
range_array

array([[[9, 6, 9],
        [6, 8, 7],
        [8, 9, 6]],

       [[5, 6, 6],
        [8, 5, 6],
        [5, 6, 9]]])

In [20]:
range_array.size

18

In [21]:
range_array.shape

(2, 3, 3)

In [22]:
random_array_2 = np.random.random((5, 3))

In [23]:
random_array_2.shape, random_array_2.size,random_array_2

((5, 3),
 15,
 array([[0.51226315, 0.38208651, 0.37172584],
        [0.35455548, 0.88766102, 0.19742678],
        [0.85608643, 0.16958965, 0.37130192],
        [0.14720514, 0.42383037, 0.85397227],
        [0.43627197, 0.95339681, 0.00162955]]))

In [24]:
# Presudo-random numbers
np.random.seed(2)

# 3. Viewing arrays and matrices 

In [27]:
np.unique(range_array)

array([5, 6, 7, 8, 9])

In [29]:
array1[0]

1

In [30]:
array2[0]

array([1, 2, 3])

In [33]:
array3[0][0][1]

2

In [39]:
array3[:2, 0:2, 0:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [40]:
array4 = np.random.randint(10, size=(2,3,4,5))

In [41]:
array4

array([[[[8, 8, 6, 2, 8],
         [7, 2, 1, 5, 4],
         [4, 5, 7, 3, 6],
         [4, 3, 7, 6, 1]],

        [[3, 5, 8, 4, 6],
         [3, 9, 2, 0, 4],
         [2, 4, 1, 7, 8],
         [2, 9, 8, 7, 1]],

        [[6, 8, 5, 9, 9],
         [9, 3, 0, 0, 2],
         [8, 8, 2, 9, 6],
         [5, 6, 6, 6, 3]]],


       [[[8, 2, 1, 4, 8],
         [1, 6, 9, 5, 1],
         [2, 4, 7, 6, 4],
         [5, 8, 3, 0, 0]],

        [[5, 7, 5, 0, 8],
         [6, 5, 1, 7, 4],
         [3, 6, 1, 4, 0],
         [8, 5, 4, 2, 9]],

        [[7, 1, 9, 2, 1],
         [0, 7, 1, 8, 9],
         [0, 7, 0, 5, 2],
         [5, 1, 3, 3, 1]]]])

In [42]:
array4.shape, array4.ndim

((2, 3, 4, 5), 4)

In [45]:
# Get the first 4 numbers of the inner most arrays
array4[:,:3,:,:1]

array([[[[8],
         [7],
         [4],
         [4]],

        [[3],
         [3],
         [2],
         [2]],

        [[6],
         [9],
         [8],
         [5]]],


       [[[8],
         [1],
         [2],
         [5]],

        [[5],
         [6],
         [3],
         [8]],

        [[7],
         [0],
         [0],
         [5]]]])